<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle()->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/generalStyle.css'))
                        ->prependStylesheet($this->basePath('css/adminStyle.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>
        <!-- Scripts -->
    </head>
    <body>
        <div class="container">
            <!-- top bar -->
            <div class="top">
                <h2>Доступ заборонено</h2>
            </div>
            <!-- left menu -->
            <div class="row">
                <div style="text-align: center" class="cols col-12">
                    <a href="/"><h1>На головну</h1></a>
                </div>
            </div>
        </div> <!-- /container -->
    </body>
</html>
