<?php $this->headTitle('Продукти'); ?>
  <div id="admin" class="content">
    <div id="addProduct">
      <a href="/admin/product/add/">+ Додати продукт</a>
    </div>
<div class="row">
  <button class="delete" onclick="methodGet()">get</button>
  <button class="delete" onclick="methodPost()">post</button>
  <button class="delete" onclick="methodPut()">put</button>
  <button class="delete" onclick="methodDelete()">delete</button>
</div>
    </table>
  </div>