<?php $this->headTitle('ROMIX SHOP');
$this->product['product_description'] = preg_replace('/\n/', '</br>', $this->product['product_description']);
$form = $this->form;
$form->setAttribute('action', $this->url('store', array('action' => 'show', 'id' => $this->id)));
?>

<div class="row">
  <div class="filtersLine">

    <div class="goBack">
      <a href="/"><- Назад</a>
    </div>

    <div class="sort">
      Sort by
      <select id="Sort">
        <option value="1">Name</option>
        <option value="5">Price</option>
      </select>
    </div>

    <div class="pagination">
      Pagination
      <select id="Pagination">
        <option value="1">1</option>
        <!--<option value="25">25</option>-->
        <option value="5">5</option>
        <option value="10">10</option>
      </select>
    </div>

  </div>
</div>

<?php
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s>
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
        &times;
      </button>
    <ul><li>')
  ->setMessageSeparatorString('</li><li>')
  ->setMessageCloseString('</li></ul></div>');

echo $flash->render('error', array('array', 'alert-dismissable', 'alert-danger'));
echo $flash->render('info', array('array', 'alert-dismissable', 'alert-info'));
echo $flash->render('default', array('array', 'alert-dismissable', 'alert-warning'));
echo $flash->render('success', array('array', 'alert-dismissable', 'alert-success'));
?>

<div class="row">
  <?php if($this->userRole == 'guest') : ?>
1
    <?php else:?>

    <div class="cols">
      <div class="showProduct">
        <h5><?=$this->product['product_name'];?></h5>
        <hr>
        <div class="data">Created: <span><?=$this->product['product_created_date'];?></span></div>
        <div class="price">Price: <span>$<?=$this->product['product_price'];?></span></div>
        <span class="inStoke">In Stoke: <span id="stoke"><?=$this->product['product_quantity'];?></span></span><br>
        <span class="description"><?=$this->product['product_description']?></span>
          <?php
          echo $this->form()->openTag($form);
          echo '<fieldset>';
          foreach ($form as $element){
            $attributes = $element->getAttributes();

            if (isset($attributes['type']) && $attributes['type'] == 'text')
            {
              echo '<div class="orderQuantity">';
              echo $this->formLabel($element);
              echo $this->formInput($element);
              echo '</div>';
            }
            elseif (isset($attributes['type']) && $attributes['type'] == 'submit')
            {
              echo '<div class="purchaseButton">';
              echo $this->formRow($element);
              echo '</div>';
            } else {
              echo $this->formRow($element);
            }
          }
          echo '</filedset>';
          echo $this->form()->closeTag();
          ?>
      </div>
    </div>

  <?php endif;?>
</div>