<?php $this->headTitle('ROMIX SHOP');
$this->product['product_description'] = preg_replace('/\n/', '</br>', $this->product['product_description']);
$form = $this->form;
?>

<div class="row">
  <div class="filtersLine">

    <div class="goBack">
      <a href="/"><- Назад</a>
    </div>

    <div class="sort">

    </div>
  </div>
</div>

<?php
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s>
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
        &times;
      </button>
    <ul><li>')
  ->setMessageSeparatorString('</li><li>')
  ->setMessageCloseString('</li></ul></div>');

echo $flash->render('error', array('array', 'alert-dismissable', 'alert-danger'));
echo $flash->render('info', array('array', 'alert-dismissable', 'alert-info'));
echo $flash->render('default', array('array', 'alert-dismissable', 'alert-warning'));
echo $flash->render('success', array('array', 'alert-dismissable', 'alert-success'));
?>

<div class="row">
  <?php if($this->userRole == 'guest') : ?>
1
    <?php else:?>

    <div class="cols">
      <div class="showProduct">
        <h5><?=$this->product['product_name'];?></h5>
        <hr>
        <div class="data">Created: <span><?=$this->product['product_created_date'];?></span></div>
        <div class="price">Price: <span>$<?=$this->product['product_price'];?></span></div>
        <span class="inStoke">In Stoke: <span id="stoke"><?=$this->product['product_quantity'];?></span></span><br>
        <span class="description"><?=$this->product['product_description']?></span>
          <div class="orderForm">
            <div class="orderQuantity">
              <label>
                Кількість
                <input name="quantity" type="text" onchange="checkQuantity()" required="required" value="1"/>
              </label>
            </div>
            <div class="purchaseButton">
              <button id="addToBesket" onclick="addProductToBasket(<?=$this->product['product_id'];?>)">Додати у корзину</button>
            </div>
          </div>
      </div>
    </div>

  <?php endif;?>
</div>