<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle()->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/generalStyle.css'))
                        ->prependStylesheet($this->basePath('css/authStyle.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/adminScripts.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/registrationScripts.js'))
            ->prependFile($this->basePath('js/jquery-2.1.4.min.js'))
//            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
        <script src="//ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.min.js"></script>

    </head>
    <body>
        <div class="container">
            <!-- top bar -->
            <div class="top">
                <div class="siteTitle"><h2><?=$this->headTitle()->renderTitle();?></h2></div>
                <div class="auth"><div class="loginButton">
                        <?=($this->headTitle()->renderTitle() == 'Реєстрація')
                          ? '<a href="/auth/login/">Ввійти</a>'
                          : '<a href="/auth/registration/">Реєстрація</a>'?>
                    </div></div>
            </div>
            <!-- left menu -->
            <?php echo $this->content; ?>
        </div> <!-- /container -->
    </body>
</html>
