<?php $this->headTitle('Замовлення'); ?>
<div id="admin" class="content">
  <table>
    <tr>
      <th>Детальна інформація</th>
      <th>№</th>
      <th>Замовник</th>
      <th>Сума замовлення</th>
      <th>Дата замовлення</th>
    </tr>
    <?php
    foreach ($this->orders AS $order)
    {
      echo '<tr>';
      echo '<td><a href="/admin/order/view/' . $order['order_id'] . '/">Переглянути</a></td>';
      echo '<td>' . $order['order_id'] . '</td>';
      echo '<td>' . $order['user_name'] . '</td>';
      echo '<td>' . $order['order_amount'] . '</td>';
      echo '<td>' . $order['order_date'] . '</td>';
      echo '</tr>';
    }
    ?>
  </table>
</div>