<?php $this->headTitle('Реєстрація'); ?>
<div class="row">
<?php
//messenger
    $flash = $this->flashMessenger();
    $flash->setMessageOpenFormat('<div%s>
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <ul><li>')
      ->setMessageSeparatorString('</li><li>')
      ->setMessageCloseString('</li></ul></div>');

    echo $flash->render('error', array('array', 'alert-dismissable', 'alert-danger'));
    echo $flash->render('info', array('array', 'alert-dismissable', 'alert-info'));
    echo $flash->render('default', array('array', 'alert-dismissable', 'alert-warning'));
    echo $flash->render('success', array('array', 'alert-dismissable', 'alert-success'));
//messenger

$form->setAttribute('action', $this->url('auth', array('action' => 'registration')));
$form->prepare();

echo $this->form()->openTag($form);
echo '<fieldset>';
  foreach ($form as $element){
  echo '<div class="formGroup">';
      echo $this->formRow($element);
      echo $this->formElementErrors($element);
  echo '</div>';
  }
  echo '</filedset>';
echo $this->form()->closeTag();
?>
</div>